server:
  port: 8888

cyh:
  logPath: /Users/nemo/Desktop/log

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

spring:
  profiles:
    active: druid